substitutions:
  plug_name: esp12f-pc5
  use_address: 192.168.90.137

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp12e
  comment: power PC5

wifi:
  !include common/wifi.config.yaml

#web_server:
#  !include common/web.config.yaml

captive_portal:
logger:
ota:
  password: !secret ota
api:
  password: !secret api
status_led:
  pin: GPIO2
dallas:
  - pin: GPIO5
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
     number: GPIO14
     mode: INPUT
     inverted: no
    name: "${plug_name} power led"
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

sensor:
  - <<: !include common/sensor/uptime.config.yaml 
  - <<: !include common/sensor/wifi_signal.config.yaml

#  - platform: dallas
#    address: 0x23021316A360AA28
#    name: "${plug_name} Temperature"

switch:
  - <<: !include common/switch/restart.config.yaml 

  - platform: gpio
    name: "${plug_name} power button"
    internal: true    
    id: pbut
    pin:
      number: GPIO12
      inverted: false

  - platform: template    
    name: "${plug_name} power"
    id: power
    icon: "mdi:power"
    turn_on_action:
    - switch.turn_on: pbut
    - delay: 500ms
    - switch.turn_off: pbut

  - platform: template    
    name: "${plug_name} power 5s"
    id: power5s
    icon: "mdi:power-settings"
    turn_on_action:
    - switch.turn_on: pbut
    - delay: 3s
    - switch.turn_off: pbut

text_sensor:
  - <<: !include common/text_sensor/online.config.yaml
  - <<: !include common/text_sensor/version.config.yaml
  - <<: !include common/text_sensor/wifi_info.config.yaml