substitutions:
  plug_name: esp12f-power-pc
  use_address: 192.168.90.137

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp12e
  comment: power PC5
  project:
    name: "WDi.PowerPC"
    version: "20210914-0"

wifi:
  !include common/wifi.config.yaml

#web_server:
#  !include common/web.config.yaml

captive_portal:
logger:
ota:
  password: !secret ota
api:
  password: !secret api
status_led:
  pin: GPIO2
dallas:
  - pin: GPIO5
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: pwled
    pin:
     number: GPIO14
     mode: INPUT
     inverted: no
    name: "${plug_name} power led"
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

sensor:
  - <<: !include common/sensor/uptime.config.yaml 
  - <<: !include common/sensor/wifi_signal.config.yaml

#  - platform: dallas
#    address: 0x23021316A360AA28
#    name: "${plug_name} Temperature"

switch:
  - <<: !include common/switch/restart.config.yaml 
  - <<: !include common/switch/power.config.yaml 
  - <<: !include common/switch/power_hold.config.yaml
  
  - platform: gpio
    name: "${plug_name} power button"
    internal: true    
    id: pbut
    pin:
      number: GPIO12
      inverted: false



text_sensor:
  - <<: !include common/text_sensor/online.config.yaml
  - <<: !include common/text_sensor/version.config.yaml
  - <<: !include common/text_sensor/wifi_info.config.yaml
