substitutions:
  plug_name: powerpc
#  use_address: 192.168.90.27

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp12e
  comment: powerPC
  project:
    name: "WDi.PowerPC"
    version: "20211222-1"
wifi:
  networks:
  - ssid: !secret ap_ssid
    password: !secret ap_password
    priority: 1.0
  - ssid: !secret ap_office_ssid
    password: !secret ap_office_password
    priority: 2.0
  ap:
    ssid: "${plug_name} Hotspot"
    password: "J4buzjhCMSA2"
  use_address: ${use_address}

web_server:
  port: 80
  auth:
    username: powerpc
    password: powerpc

captive_portal:
logger:
ota:
  password: !secret ota
api:
  password: !secret api
status_led:
  pin: GPIO2
dallas:
  - pin: GPIO5
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: pwled
    pin:
     number: GPIO14
     mode: INPUT
     inverted: no
    name: "${plug_name} power led"
    icon: mdi:led-outline
    filters:
      - delayed_on: 1s
      - delayed_off: 1s

sensor:
  - platform: uptime
    id: device_uptime
    internal: true
  - platform: wifi_signal
    name: "${plug_name} WiFi"
    update_interval: 60s
#  - platform: dallas
#    address: 0x23021316A360AA28
#    name: "${plug_name} Temperature"

switch:
  - platform: restart
    name: "${plug_name} restart"

  - platform: template
    name: "${plug_name} power"
    icon: "mdi:power"
    lambda: |-
      if (id(pwled).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: pbut
      - delay: 1500ms
      - switch.turn_off: pbut
    turn_off_action:
      - switch.turn_on: pbut
      - delay: 1500ms
      - switch.turn_off: pbut
  
  - platform: gpio
    name: "${plug_name} power button"
    #    icon: mdi:wall-sconce-flat
    internal: true    
    id: pbut
    pin:
      number: GPIO12
      inverted: false
    #      mode: INPUT_PULLDOWN

  - platform: template
    name: "${plug_name} power hold"
    icon: "mdi:power-settings"
    lambda: |-
      if (id(pwled).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: pbut
      - delay: 5s
      - switch.turn_off: pbut
    turn_off_action:
      - switch.turn_on: pbut
      - delay: 5s
      - switch.turn_off: pbut
  

text_sensor:
  - platform: template
    name: "${plug_name} online"
    lambda: |-
      uint32_t uptime = (id(device_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
        return { (String(minutes) + " мин.").c_str() };
      }
    update_interval: 60s
    icon: mdi:clock-start

  - platform: version
    name: "${plug_name} Version"
    hide_timestamp: True

  - platform: wifi_info
    ip_address:
      name: "${plug_name} ip_address"
      icon: "mdi:ip"
