switch:
  - platform: restart
    name: "${plug_name} restart"

sensor:
#  - platform: uptime
#    id: device_uptime
#    internal: true

  - platform: uptime
    name: Uptime Sensor
    internal: true
    id: device_uptime
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(device_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "д " : "") +
                (hours ? String(hours) + "ч " : "") +
                (minutes ? String(minutes) + "м " : "") +
                (String(seconds) + "с")
              ).c_str();    

  - platform: wifi_signal
    name: "${plug_name} WiFi"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${plug_name} Version"
    hide_timestamp: True

  - platform: template
    name: "${plug_name} online"
    id: uptime_human
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: "${plug_name} ip_address"
      icon: "mdi:ip"
