switch:
  - platform: restart
    name: "${plug_name} restart"

sensor:
#  - platform: uptime
#    id: device_uptime
#    internal: true

  - platform: wifi_signal
    name: "${plug_name} WiFi"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${plug_name} Version"
    hide_timestamp: True

  - platform: template
    name: "${plug_name} online"
    lambda: |-
      uint32_t uptime = (id(device_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
        return { (String(minutes) + " мин.").c_str() };
      }
    update_interval: 60s
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: "${plug_name} ip_address"
      icon: "mdi:ip"
