  networks:
  - ssid: !secret ap_ssid
    password: !secret ap_password
    priority: 1.0
  - ssid: !secret ap_office_ssid
    password: !secret ap_office_password
    priority: 2.0
  ap:
    ssid: "${plug_name} Hotspot"
    password: "G4bDzjBCdwA5"
  use_address: ${use_address}