platform: template
name: "${plug_name} power hold"
icon: "mdi:power-settings"
lambda: |-
  if (id(pwled).state) {
    return true;
  } else {
    return false;
  }
turn_on_action:
  - switch.turn_on: pbut
  - delay: 5s
  - switch.turn_off: pbut
turn_off_action:
  - switch.turn_on: pbut
  - delay: 5s
  - switch.turn_off: pbut
